window.Games.coinflip = function () {
  const stage = document.getElementById('game-stage');
  stage.innerHTML = `
    <div class="table-felt">
      <h2>🪙 High-Stakes Flip</h2>
      <div class="coin-box">
        <div class="coin" id="coin">
          <div class="side heads">👤</div>
          <div class="side tails">🦅</div>
        </div>
      </div>
      <div id="cf-betmount"></div>
      <div style="display:flex; gap:12px; justify-content:center;">
        <button class="pill" id="flip-h" style="padding:12px 32px;">Heads</button>
        <button class="pill secondary" id="flip-t" style="padding:12px 32px;">Tails</button>
      </div>
      <p id="coin-msg" style="margin-top: 14px; font-weight: bold; min-height: 24px;"></p>
    </div>
  `;

  const bet = CasinoShared.betPanel(document.getElementById('cf-betmount'), { value: 50 });
  const btnH = document.getElementById('flip-h');
  const btnT = document.getElementById('flip-t');
  const msg = document.getElementById('coin-msg');

  const flipCoin = async (choice) => {
    const b = bet.get();
    if (b <= 0) { msg.textContent = 'Enter a valid bet.'; return; }
    if (window.GameAPI.cachedBalance != null && b > window.GameAPI.cachedBalance) {
      msg.textContent = 'Not enough chips.'; return;
    }
    btnH.disabled = true; btnT.disabled = true;
    msg.textContent = '';
    const coin = document.getElementById('coin');
    coin.className = 'coin';
    try {
      const d = await window.GameAPI.play({ game: 'coinflip', bet: b, choice });
      setTimeout(() => coin.classList.add(d.flip === 'heads' ? 'flip-heads' : 'flip-tails'), 50);
      setTimeout(() => {
        msg.textContent = d.result;
        if (d.flip === choice) CasinoShared.playSound('win');
        btnH.disabled = false; btnT.disabled = false;
      }, 2050);
    } catch (e) {
      msg.textContent = e.message;
      btnH.disabled = false; btnT.disabled = false;
    }
  };

  btnH.addEventListener('click', () => flipCoin('heads'));
  btnT.addEventListener('click', () => flipCoin('tails'));

  CasinoShared.addGameInfo(stage, { title: 'More info', html: `<p>Choose heads or tails and place a wager. A correct pick pays 1:1 profit; an incorrect pick loses the wager.</p><p class="game-info-note">Each flip is generated by the server and has an equal chance of landing on either side.</p>` });
};